package email

import (
	"fmt"
	"html"
	"regexp"
	"strings"
	"time"

	"aiweb3news/internal/storage"
)

var (
	prefixRe = regexp.MustCompile(`(?:<p>)?深潮 TechFlow 消息，\d{1,2} 月 \d{1,2} 日，`)
	imgRe    = regexp.MustCompile(`<img[^>]+>`)
)

func cleanSummary(s string) string {
	s = imgRe.ReplaceAllString(s, "")
	s = prefixRe.ReplaceAllString(s, "<p>")
	s = strings.TrimRight(s, " \t\r\n")
	return s
}

// BuildDailyDigestHTML creates an HTML email body for a daily digest.
// Returns empty string if there are no items.
func BuildDailyDigestHTML(items []storage.StoredItem, date time.Time) string {
	if len(items) == 0 {
		return ""
	}

	var b strings.Builder

	b.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background:#f0f2f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f0f2f5;">
<tr><td align="center" style="padding:24px 12px;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="width:100%;">

<!-- Header -->
<tr><td style="background:#0f172a;border-radius:16px 16px 0 0;padding:0;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0">
<tr><td style="padding:36px 32px 16px;text-align:center;">
<span style="display:inline-block;font-family:Georgia,'Times New Roman',serif;font-size:32px;font-weight:700;color:#f1f5f9;letter-spacing:6px;text-transform:uppercase;">WEB3 NEWS</span>
</td></tr>
<tr><td style="padding:0 32px 8px;text-align:center;font-family:Georgia,'Times New Roman',serif;font-size:15px;color:#94a3b8;letter-spacing:1px;text-transform:uppercase;">Daily Digest</td></tr>
<tr><td style="padding:14px 32px 28px;text-align:center;font-size:12px;color:#64748b;letter-spacing:1px;">` + date.Format("January 02, 2006") + `</td></tr>
</table>
</td></tr>

<!-- Body -->
<tr><td style="background:#ffffff;padding:0 28px;">

`)

	for i, item := range items {
		b.WriteString(`<table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding:22px 0;`)
		if i < len(items)-1 {
			b.WriteString(`border-bottom:1px solid #edf0f5;`)
		}
		b.WriteString(`">`)

		// Title
		b.WriteString(fmt.Sprintf(`<h2 style="margin:0 0 8px;font-size:16px;line-height:1.5;font-weight:600;"><a href="%s" style="color:#0f172a;text-decoration:none;border-bottom:1px solid transparent;">%s</a></h2>`,
			html.EscapeString(item.Link), html.EscapeString(item.Title)))

		// Summary
		b.WriteString(fmt.Sprintf(`<div style="font-size:14px;line-height:1.7;color:#64748b;">%s</div>`, cleanSummary(item.Summary)))

		b.WriteString(`</td></tr></table>`)
	}

	b.WriteString(`</td></tr>

<!-- Footer -->
<tr><td style="background:#f8fafc;border-radius:0 0 16px 16px;padding:24px 32px;border-top:1px solid #edf0f5;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0">
<tr><td style="font-size:11px;color:#94a3b8;">Generated by Web3 Info AI</td>
<td align="right" style="font-size:11px;color:#cbd5e1;">` + date.Format("2006-01-02") + `</td>
</tr></table>
</td></tr>
</table>
</td></tr>
</table>
</body>
</html>`)

	return b.String()
}